# APPLICATION
spring.application.name=ecommerce-backend
server.port=8080

# DATABASE (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# PAYPAL
paypal.client.id=AVTvEyzyicb6yDsTeJKu4bMZeA7cJHceEAB6gxjf6rTeMOV3J6nncXGmsv9XLQF5O6H2i67yUaYwD0sn
paypal.client.secret=EPE5_xPG9rIjGeWLhW3tAdPTeCql6QD77RtKhKPz1nD_DcLEl6snUX0lTix_2uu3A8URr5zezv1MWG7B
paypal.mode=sandbox

# LOGGING
logging.level.org.springframework.security=TRACE
logging.level.com.ecommerce.backend.security=DEBUG